# Generated by Django 2.2.7 on 2019-11-16 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myScoreboard', '0002_auto_20191116_2259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['-team_points']},
        ),
    ]
